Feature: Board Locations

  Scenario: Board locations
    When A board is created
    Then location 0 is "Go"
    Then location 1 is "Old Kent Road"
    Then location 2 is "Community Chest 1"
    Then location 3 is "Whitechapel Road"
    Then location 4 is "Income Tax"
    Then location 5 is "Kings Cross Station"
    Then location 6 is "The Angel Islington"
    Then location 7 is "Chance 1"
    Then location 8 is "Euston Road"
    Then location 9 is "Pentonville Road"
    Then location 10 is "Just Visiting / Jail"
    Then location 11 is "Pall Mall"
    Then location 12 is "Electric Company"
    Then location 13 is "Whitehall"
    Then location 14 is "Northumberland Avenue"
    Then location 15 is "Marylebone Station"
    Then location 16 is "Bow Street"
    Then location 17 is "Community Chest 2"
    Then location 18 is "Marlborough Street"
    Then location 19 is "Vine Street"
    Then location 20 is "Free Parking"
    Then location 21 is "Strand"
    Then location 22 is "Chance 2"
    Then location 23 is "Fleet Street"
    Then location 24 is "Trafalgar Square"
    Then location 25 is "Fenchurch Street Station"
    Then location 26 is "Leicester Square"
    Then location 27 is "Coventry Street"
    Then location 28 is "Water Works"
    Then location 29 is "Piccadilly"
    Then location 30 is "Go To Jail"
    Then location 31 is "Regent Street"
    Then location 32 is "Oxford Street"
    Then location 33 is "Community Chest"
    Then location 34 is "Bond Street"
    Then location 35 is "Liverpool Street Station"
    Then location 36 is "Chance"
    Then location 37 is "Park Lane"
    Then location 38 is "Super Tax"
    Then location 39 is "Mayfair"